# Book settings
title: My sample book
author: The Jupyter Book Community
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/dropout009/jbtest
html:
  use_issues_button: true
