# Book settings
title: My First Jupyter Book
author: dropout009
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/dropout009/jbtest
html:
  use_repository_button: true
